name: Setup Poetry tool
description: Set up Poetry tool.
author: Sia Codelabs

branding:
  icon: play-circle
  color: gray-dark

inputs:
  setup-python:
    description: Install Python.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: sudo apt install -y curl

    - name: Set up Python if requested
      if: inputs.setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
