name: Example

on: workflow_dispatch

permissions:
  contents: write

jobs:
  call:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Set up Poetry
        uses: siacodelabs/setup-poetry@v1
      
      - name: Check installation
        run: poetry --version
